// Auto-generated by scripts/sync-resume.ts — do not edit manually
// Last synced: 2026-03-20T16:59:21.153Z

export const domains = ["ML & AI","Cloud & DevOps","Systems & Backend","IoT & Embedded","Mobile","Game Dev & XR","Full Stack & Web"] as const;
export type Domain = typeof domains[number];

export const bio = {
  name: 'Po Haoting',
  roles: ['ML Research Assistant', 'Systems Engineer', 'Cloud Architect', 'Full Stack Developer'],
  summary: 'Computing Science undergraduate at SIT–University of Glasgow, currently developing custom model architectures for long-horizon time-series prediction as an ML Research Assistant. Former cloud software engineering intern at Razer and WorldSkills Singapore 2018 competitor. Ngee Ann Kongsi Scholar and SCDF & Dell Innovation Challenge 2025 Top 10 Finalist.',
  email: 'pohaoting@gmail.com',
  github: 'https://github.com/hoshinoht',
  linkedin: 'https://www.linkedin.com/in/po-haoting/',
};

export interface Experience {
  id: string;
  company: string;
  title: string;
  period: string;
  type: 'research' | 'internship';
  skills: string[];
  bullets: string[];
  domains: Domain[];
}

export const experiences: Experience[] = [
  {
    id: 'sit-ml-ra',
    company: 'Singapore Institute of Technology',
    title: 'Research Assistant – Machine Learning',
    period: 'Feb 2026 – Present',
    type: 'research',
    skills: [
      'Deep Learning',
      'LSTM',
      'GRU',
      'LLM',
      'Python',
      'Literature Review',
    ],
    bullets: [
      'Engineered LSTM, GRU, and LLM-based frameworks to benchmark long-horizon time-series prediction across heterogeneous datasets; resulting models were adopted as the team\'s primary forecasting baselines',
      'Reviewed state-of-the-art ML literature to identify architectural gaps in long-horizon forecasting and recommended research directions that shaped the team\'s experimental roadmap',
      'Documented reproducible training pipelines and evaluation protocols, allowing the team to iterate on and replicate results across dataset variants',
    ],
    domains: [
      'ML & AI',
    ],
  },
  {
    id: 'sit-vr-ra',
    company: 'Singapore Institute of Technology',
    title: 'Research Assistant – Virtual Environment Development',
    period: 'Apr 2025 – Jul 2025',
    type: 'research',
    skills: [
      'Unity',
      'C#',
      'VR',
      'Game Development',
      'Digital Wellness',
    ],
    bullets: [
      'Developed a full Unity game loop (tower placement, enemy pathfinding, wave management, object pooling) as a reusable research tool for digital wellness studies with integrated mindfulness interventions',
      'Built interactive Unity environments with real-time progression tracking and participant-facing UI to support controlled, replicable digital wellness experiments',
    ],
    domains: [
      'Systems & Backend',
      'Game Dev & XR',
    ],
  },
  {
    id: 'razer-swe',
    company: 'Razer',
    title: 'Software Engineering (Cloud) Intern',
    period: 'Apr 2022 – Sep 2022',
    type: 'internship',
    skills: [
      'C#',
      '.NET',
      'Cloud',
      'Monitoring',
      'UI Optimization',
      'Backend Architecture',
      'React',
      'Electron',
      'TypeScript',
    ],
    bullets: [
      'Profiled and optimised Razer Synapse 4 UI components through iterative code reviews and performance analysis, reducing average load times by 15% across key user interaction flows',
      'Built monitoring and observability tooling in Agile sprints, reducing incident detection and resolution time across engineering teams',
      'Helped redesign backend service architecture with CI/CD-integrated deployments, improving pipeline reliability and service throughput',
    ],
    domains: [
      'Cloud & DevOps',
      'Systems & Backend',
      'Game Dev & XR',
      'Full Stack & Web',
    ],
  },
  {
    id: 'razer-qa',
    company: 'Razer',
    title: 'QA Engineer Intern',
    period: 'Mar 2021 – Sep 2021',
    type: 'internship',
    skills: [
      'Python',
      'Test Automation',
      'QA',
      'Selenium',
    ],
    bullets: [
      'Developed Python/Selenium automated regression scripts for Razer Synapse, reducing manual test cycle time and expanding hardware-software integration coverage',
      'Ran end-to-end test suites across Razer hardware and software products, surfacing defects that were blocking release milestones',
    ],
    domains: [],
  },
  {
    id: 'wishbone',
    company: 'Wishbone Digital Group',
    title: 'Full Stack Developer Intern',
    period: 'Jan 2019 – Mar 2019',
    type: 'internship',
    skills: [
      'PHP',
      'JavaScript',
      'HTML',
      'CSS',
      'Full-Stack Web Development',
    ],
    bullets: [
      'Built and maintained PHP/JavaScript web applications for multiple client projects, delivering on schedule at a digital media agency',
      'Translated client briefs into HTML/CSS/JS UI components and backend endpoints, shipping features iteratively across active projects',
    ],
    domains: [
      'Full Stack & Web',
    ],
  },
];

export interface Project {
  id: string;
  name: string;
  summary: string;
  period: string;
  type: 'team' | 'solo';
  repo?: string;
  responsibilities: string[];
  impact: string[];
  tech: string[];
  featured: boolean;
  domains: Domain[];
}

export const projects: Project[] = [
  {
    id: 'carehaven',
    name: 'CareHaven',
    summary: 'Full-stack caregiver platform for seniors with microservices, real-time alerts, and observability',
    period: 'Oct 2025 – Present',
    type: 'team',
    repo: 'https://github.com/n2-carehaven (local)',
    responsibilities: [
      'Architected gRPC API Gateway with Firebase auth and rate limiting',
      'Built event-driven backend with Wolverine/RabbitMQ messaging',
      'Developed haven CLI (5,100+ LOC Go) for Docker orchestration, proto codegen, TLS, and Flutter builds',
      'Implemented Prometheus + Tempo + Grafana observability stack with distributed tracing',
      'Developed federated learning autoencoder for vital sign anomaly detection (>95% detection, <5% false positives)',
      'Implemented SOS crisis management with heartbeat monitoring and Telegram escalation',
    ],
    impact: [
      '10+ container production stack with dual-protocol mobile app (gRPC-first, REST fallback)',
      'Sub-second SOS alert delivery via Redis pub/sub + FCM push notifications',
      '700+ commits across all submodules',
    ],
    tech: [
      'C#',
      'Dart',
      'Go',
      'Python',
      'Kotlin',
      '.NET 10',
      'Flutter',
      'Unity',
      'Docker',
      'PostgreSQL',
      'Valkey/Redis',
      'RabbitMQ',
      'Firebase',
      'gRPC',
      'REST',
      'Event-Driven Architecture',
      'Microservices',
      'OpenTelemetry Tracing',
      'Prometheus',
      'Grafana',
      'Grafana Tempo',
      'Locust',
      'pytest',
    ],
    featured: true,
    domains: [
      'ML & AI',
      'Cloud & DevOps',
      'Systems & Backend',
      'Mobile',
      'Game Dev & XR',
      'Full Stack & Web',
    ],
  },
  {
    id: 'digital-kopitiam',
    name: 'Digital Kopitiam Android',
    summary: 'Real-time social platform with gRPC microservices, WebRTC video, and Android client',
    period: 'Nov 2025 – Present',
    type: 'team',
    repo: 'https://github.com/hoshinoht/digital-kopitiam',
    responsibilities: [
      'Designed and built 5 gRPC microservices in Go (Auth, Room, Signaling, Presence, Wellness) with pure gRPC transport and Buf protobuf codegen',
      'Implemented WebRTC SFU for video calling',
      'Built Android client in Kotlin with Jetpack Compose and gRPC-OkHttp, backed by SQLite, Valkey, and RabbitMQ',
      'Containerised all services with Docker',
    ],
    impact: [
      'Fully functional real-time platform with pure-gRPC microservice isolation and Jetpack Compose mobile client',
      'Live presence heartbeats and JWT auth',
    ],
    tech: [
      'Go',
      'Kotlin',
      'gRPC',
      'WebRTC',
      'Docker',
      'Microservices',
      'JWT Auth',
      'WebRTC SFU',
    ],
    featured: true,
    domains: [
      'Cloud & DevOps',
      'Systems & Backend',
      'Mobile',
    ],
  },
  {
    id: 'virtualkopis',
    name: 'VirtualKopis',
    summary: 'Cloud-native WebRTC video chat platform for seniors with Kubernetes backend and React frontend',
    period: 'Sep 2025 – Dec 2025',
    type: 'team',
    repo: 'https://github.com/hoshinoht/virtualkopis',
    responsibilities: [
      'Built API Gateway, Room Service, Game Service, and Signalling Server in Rust',
      'Deployed backend services to Kubernetes cluster',
      'Implemented mediasoup SFU for WebRTC video, O(N) bandwidth scaling to 10-15 concurrent participants at 720p@30fps with <2% packet loss',
      'Developed React 18 + TypeScript frontend',
    ],
    impact: [
      '13 themed virtual rooms with real-time video, messaging, and interactive games',
      '52% CPU utilisation at 15 concurrent participants; 1200ms avg connection time',
    ],
    tech: [
      'Rust',
      'TypeScript',
      'JavaScript',
      'React',
      'Actix Web',
      'Kubernetes',
      'Docker',
      'Redis',
      'Microservices',
      'WebRTC',
      'WebSocket Signalling',
      'gRPC',
      'Prometheus',
      'Grafana',
      'mediasoup',
    ],
    featured: true,
    domains: [
      'Cloud & DevOps',
      'Systems & Backend',
      'Full Stack & Web',
    ],
  },
  {
    id: 'forest-link-protocol',
    name: 'Forest Link Protocol (FLP)',
    summary: 'Adaptive multi-protocol IoT mesh for dense forest environments using BLE, LoRa, and MQTT-SN on ESP32',
    period: 'Jan 2026 – Apr 2026',
    type: 'team',
    repo: 'https://github.com/hoshinoht/forest-link-protocol',
    responsibilities: [
      'Designed adaptive multi-protocol mesh with BLE, LoRa, and WiFi/MQTT-SN layers',
      'Implemented Selective Repeat ARQ sliding window for reliable delivery',
      'Built interrupt-driven packet processing with FreeRTOS priority tuning (ISR@20, routing@15, MQTT@10)',
      'Engineered 8-byte compact packet header for LoRa\'s 247B / BLE\'s 504B constrained MTU',
      'Developed O(1) memory-mapped fragment reassembly using ESP32-S3 8MB PSRAM',
      'Enforced Barr-C:2018 embedded coding standards via clangd + .clang-format',
    ],
    impact: [
      '1 MB file transfer over 3+ hops within 20 minutes',
      '3 MB transfer capability across 3+ hops in deep forest conditions',
    ],
    tech: [
      'C++',
      'C',
      'Python',
      'ESP-IDF',
      'FreeRTOS',
      'MQTT',
      'BLE Mesh',
      'LoRa Mesh',
      'Selective Repeat ARQ',
      'Adaptive Protocol Selection',
    ],
    featured: true,
    domains: [
      'Systems & Backend',
      'IoT & Embedded',
    ],
  },
  {
    id: 'mqttsn-picow',
    name: 'MQTT-SN IoT File Transfer System',
    summary: 'Reliable file transfer between IoT devices using MQTT-SN/UDP on FreeRTOS with custom hardware drivers',
    period: 'Sep 2025 – Dec 2025',
    type: 'team',
    repo: 'https://github.com/hoshinoht/mqttsn-picow',
    responsibilities: [
      'Implemented FreeRTOS multithreaded architecture with MQTT-SN over UDP',
      'Built Go-Back-N ARQ with 32KB sliding window for reliable delivery with QoS 0–2 (5–15 KB/s throughput, 237B chunks)',
      'Engineered custom exFAT microSD driver in C via SPI',
      'Developed real-time Node.js + Socket.IO monitoring dashboard for device telemetry and command control',
      'Implemented hot-plug microSD card detection with dual console+SD logging',
    ],
    impact: [
      'Robust chunked file transfer with configurable QoS',
      'Hardware-level storage with live observability',
    ],
    tech: [
      'C',
      'FreeRTOS',
      'MQTT-SN',
      'UDP',
      'Go-Back-N ARQ',
      'QoS 0-2',
      'Chunked Transfer',
    ],
    featured: false,
    domains: [
      'IoT & Embedded',
    ],
  },
  {
    id: 'microsd-driver',
    name: 'MicroSD Driver for Pico W',
    summary: 'exFAT-compatible microSD card driver for Raspberry Pi Pico W using SPI communication',
    period: 'Sep 2025 – Dec 2025',
    type: 'solo',
    repo: 'https://github.com/hoshinoht/microsd-driver-for-pico-w',
    responsibilities: [
      'Implemented exFAT filesystem driver from scratch in C with automatic file versioning and bitwise parsing of MBR, boot sectors, and allocation bitmaps',
      'Built SPI communication layer for microSD card interface',
    ],
    impact: [
      'Reusable hardware driver for Pico W; 1KB static RAM, ~500ms init, ~50–100ms file operations',
    ],
    tech: [
      'C',
      'SPI',
      'exFAT Filesystem',
    ],
    featured: false,
    domains: [
      'IoT & Embedded',
    ],
  },
  {
    id: 'silveragent',
    name: 'SilverAgent',
    summary: 'AI-powered senior super app with fine-tuned SEA-LION LLM and multi-agent architecture',
    period: 'Dec 2025 – Dec 2025',
    type: 'team',
    repo: 'https://github.com/hoshinoht/SilverAgent',
    responsibilities: [
      'Built multi-agent AI system with structured reasoning pipeline and intent detection across healthcare, transport, and weather domains',
      'Fine-tuned SEA-LION LLM for Singapore context (English + Singlish)',
      'Designed senior-friendly adaptive UI with dynamic scaling (0.8x to 2.5x), UUID-persistent sessions, and Provider state management',
    ],
    impact: [
      'Working multi-agent super app with natural language understanding across service domains',
      'Proactive assistance: weather checks before appointments, transport booking suggestions',
    ],
    tech: [
      'Dart',
      'Python',
      'Flutter',
      'Multi-Agent System',
      'LLM Fine-Tuning',
      'SEA-LION LLM',
      'HuggingFace',
    ],
    featured: true,
    domains: [
      'ML & AI',
      'Mobile',
    ],
  },
  {
    id: 'zensupply',
    name: 'Zensupply',
    summary: 'Predictive inventory management with ML pipeline and GenAI-driven insights',
    period: 'Feb 2025 – Mar 2025',
    type: 'team',
    repo: 'https://github.com/hoshinoht/Zensupply',
    responsibilities: [
      'Developed ensemble ML pipeline (Linear Regression, Random Forest, Gradient Boosting) with temporal feature engineering (lag features, rolling averages) for demand forecasting',
      'Integrated Gemini/OpenAI/Azure LLMs with RAG to generate real-time inventory insights, including demand forecasts, safety stock levels, and restock quantities',
    ],
    impact: [
      'Improved restocking accuracy through ensemble ML forecasting and context-aware recommendations powered by multiple LLMs',
    ],
    tech: [
      'Python',
      'Scikit-learn',
      'Flask',
      'RAG Architecture',
      'ML Pipeline',
      'Gemini API',
    ],
    featured: false,
    domains: [
      'ML & AI',
      'Systems & Backend',
    ],
  },
  {
    id: 'online-handwriting-similarity',
    name: 'Online Handwriting Similarity Model',
    summary: 'Deep learning model for Chinese handwriting recognition with structural similarity scoring',
    period: 'Nov 2025 – Present',
    type: 'solo',
    repo: 'https://github.com/hoshinoht/online-handwriting-similarity',
    responsibilities: [
      'Designed ResNet-1D + BiGRU + Attention backbone for stroke feature extraction',
      'Implemented ArcFace angular margin loss (m=0.5, s=30) for metric learning across thousands of visually similar Chinese characters',
      'Built dual-head output: character classification + structural similarity scoring',
      'Compressed model via lottery ticket pruning (90–95% weight reduction) and ONNX INT8 quantization for sub-millisecond mobile inference',
    ],
    impact: [
      'Edge-deployable model via ONNX INT8 quantization with sub-millisecond inference; 60–90%+ continuous accuracy scoring rubric',
    ],
    tech: [
      'Python',
      'PyTorch',
      'ResNet-1D',
      'BiGRU',
      'Attention Pooling',
      'ArcFace Loss',
    ],
    featured: true,
    domains: [
      'ML & AI',
    ],
  },
  {
    id: 'ges-monitoring',
    name: 'Graduate Employment Survey System',
    summary: 'Dual-backend survey management system comparing SQL vs NoSQL with interactive analytics',
    period: 'Apr 2025 – Jul 2025',
    type: 'team',
    repo: 'https://github.com/hoshinoht/ges-monitoring-system',
    responsibilities: [
      'Built Rust/Actix Web + SQLite backend with compile-time query verification (SQLx) and microsecond-precision performance timing',
      'Built Python/Flask + MongoDB backend with aggregation pipelines',
      'Developed SPA frontend with dynamic backend switching and real-time performance comparison',
    ],
    impact: [
      'Side-by-side SQL vs NoSQL benchmarking with cross-platform build (Windows/macOS/Linux) and full CI (cargo clippy + pytest)',
      '1,450 records across Singapore university employment data (2013-2024)',
    ],
    tech: [
      'Rust',
      'Python',
      'JavaScript',
      'Actix Web',
      'Flask',
      'SQLite',
      'MongoDB',
      'Dual Backend',
      'REST API',
      'Aggregation Pipelines',
      'Chart.js',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Full Stack & Web',
    ],
  },
  {
    id: '3124-capstone',
    name: 'IT-Engineering Coordination Dashboard',
    summary: 'Full-stack collaboration dashboard for IT-Engineering teams with task management and equipment booking',
    period: 'Oct 2025 – Dec 2025',
    type: 'team',
    repo: 'https://github.com/hoshinoht/3124-capstone-prototype',
    responsibilities: [
      'Built Rust backend with Actix Web and SQLite',
      'Developed React + TypeScript frontend (Tailwind CSS, shadcn/ui) with booking conflict detection, task urgency tagging, personnel check-in, and HVAC/BMS glossary search',
    ],
    impact: [
      'Unified IT-Engineering workflow into a single dashboard covering calendar, equipment booking with conflict detection, task management, personnel tracking, and HVAC/BMS glossary search',
    ],
    tech: [
      'Rust',
      'TypeScript',
      'Actix Web',
      'React',
      'Vite',
      'SQLite',
      'JWT',
      'REST',
      'Tailwind CSS',
      'shadcn/ui',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Full Stack & Web',
    ],
  },
  {
    id: 'budget-tracker',
    name: 'Budget Tracker',
    summary: 'Monthly budget tracking web app with Rust/Axum backend and MongoDB',
    period: 'Nov 2025 – Dec 2025',
    type: 'solo',
    repo: 'https://github.com/hoshinoht/budget-tracker',
    responsibilities: [
      'Built full-stack Axum web app with Tera templating',
      'Implemented thread-safe concurrency with DashMap and parking_lot',
      'Containerised with Docker Compose (app + MongoDB + Mongo Express)',
    ],
    impact: [
      'High-performance caching layer with optimized connection pooling',
    ],
    tech: [
      'Rust',
      'Axum',
      'MongoDB',
      'Docker',
      'Thread-Safe Concurrency',
      'Connection Pooling',
      'Caching',
      'Material Design Lite',
    ],
    featured: false,
    domains: [
      'Cloud & DevOps',
      'Systems & Backend',
      'Full Stack & Web',
    ],
  },
  {
    id: 'air-power-domination',
    name: 'Air Power Domination',
    summary: '4v4 multiplayer PvP RTS built in Unity for RSAF, featuring LAN networking, role-based gameplay, and real-time building and airstrike mechanics',
    period: 'Sep 2021 – Apr 2022',
    type: 'team',
    repo: 'https://github.com/hoshinoht/air-power-domination',
    responsibilities: [
      'Built LAN multiplayer networking layer using Unity Netcode with synchronised game state across 8 concurrent players',
      'Developed real-time UI systems for commander decision-making, unit selection, building placement, and resource management',
      'Implemented core gameplay systems: preparation/action phase transitions, airstrikes, recon, and building construction (Command Center, Watchtower, SAM Site, Hangar, Runway)',
      'Designed role-based gameplay (Commander, Engineer, Weapons Specialist, Guard) with distinct abilities and UI per role',
      'Built camera controls (WASD + mouse) and unit selection/movement systems',
      'Developed custom shader pipeline (HLSL/ShaderLab) for visual effects across a 130×10 grid battlefield',
    ],
    impact: [
      '2M+ LOC C# codebase; fully functional LAN multiplayer game',
      'Final Year Project for Singapore Polytechnic / RSAF client',
      '2-team (4v4) PvP matches on 130x10 grid map',
    ],
    tech: [
      'C#',
      'Unity',
      'Unity Netcode',
      'LAN Multiplayer',
      'Real-Time Strategy',
      'Role-Based Gameplay',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Game Dev & XR',
    ],
  },
  {
    id: 'project-sylvestris-vr',
    name: 'Project Sylvestris VR',
    summary: 'VR barista training simulator built in Unity for mobile VR, featuring realistic interaction mechanics, in-VR UI, and simulation-based skill training',
    period: 'Mar 2021 – May 2021',
    type: 'team',
    repo: 'https://github.com/hoshinoht/Project-Sylvestris-VR',
    responsibilities: [
      'Developed VR barista training simulator in Unity for mobile VR headsets with multi-shader rendering pipeline (GLSL + HLSL)',
      'Implemented VR interaction mechanics for equipment handling and drink preparation, simulating realistic barista workflows',
      'Built in-VR UI systems for training guidance, feedback, and progression tracking',
      'Designed structured practice scenarios with progressive difficulty for barista skill acquisition',
    ],
    impact: [
      '2M+ LOC C# VR project',
      'Simulation-based training tool for barista skill development',
    ],
    tech: [
      'C#',
      'Unity',
      'VR',
      'XR',
      'Simulation',
      'VR Interaction',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Game Dev & XR',
    ],
  },
  {
    id: 'ra-virtual-td',
    name: 'Keep Calm! Mindfulness Mission',
    summary: 'Tower defense game in Unity with full game loop (building, upgrades, pathfinding, wave management, object pooling) and mindfulness techniques for digital wellness research',
    period: 'Feb 2025 – Jul 2025',
    type: 'solo',
    repo: 'https://github.com/hoshinoht/ra-virtual-td',
    responsibilities: [
      'Built tower placement and upgrade system with BuildingNode management and shop/blueprint UI for tower selection',
      'Implemented enemy pathfinding along predefined paths and wave management controlled by LevelManager',
      'Developed resource management system (currency for building and upgrading towers) with real-time UI feedback',
      'Engineered object pooling (PoolManager) for efficient instantiation of enemies and projectiles',
      'Built scene management system for loading levels and menus',
      'Integrated mindfulness-based progress tracking techniques into gameplay for digital wellness research',
    ],
    impact: [
      'Research tool combining gaming with digital wellness interventions',
      'Complete tower defense game loop with building, upgrades, and wave progression',
    ],
    tech: [
      'C#',
      'Unity',
      'Tower Defense',
      'Object Pooling',
      'Wave Management',
      'Pathfinding',
      'Scene Management',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Game Dev & XR',
    ],
  },
  {
    id: 'omagatoki',
    name: 'Omagatoki',
    summary: '3D Japanese fantasy tower defence game in Unity with pathfinding, UI systems, and level design',
    period: 'Jan 2021 – Jun 2021',
    type: 'team',
    repo: 'https://github.com/hoshinoht/omagatoki',
    responsibilities: [
      'Designed and implemented UI systems for tower selection, placement, and in-game feedback',
      'Built core game mechanics: tower placement, enemy spawning, damage systems, and win/lose conditions',
      'Implemented enemy pathfinding algorithms and wave progression logic',
      'Designed multiple game levels with escalating difficulty and varied layouts',
    ],
    impact: [
      'Complete 3D tower defence game with Japanese fantasy theme',
    ],
    tech: [
      'C#',
      'Unity',
      'Tower Defense',
      'Pathfinding',
      'Level Design',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Game Dev & XR',
    ],
  },
  {
    id: 'android-mesh-visualiser',
    name: 'MeshGraph',
    summary: 'AR-enabled Android app for P2P mesh network visualization using Nearby Connections, ARCore Cloud Anchors, and Bully Algorithm leader election',
    period: 'Jan 2026 – Present',
    type: 'team',
    repo: 'https://github.com/hoshinoht/android-mesh-visualiser',
    responsibilities: [
      'Implemented P2P peer discovery and mesh topology visualization using Google Nearby Connections over BLE/WiFi',
      'Built AR overlay rendering network nodes and links in 3D space with ARCore Cloud Anchors for cross-device spatial sync',
      'Developed Bully Algorithm leader election with OK/COORDINATOR messaging for distributed coordination',
      'Created interactive CSMA/CD protocol simulator with collision visualization and packet animation',
      'Designed dynamic quiz engine that generates questions from live mesh network state',
    ],
    impact: [
      'Educational tool demonstrating distributed networking concepts (leader election, CSMA/CD, mesh topology) through AR interaction',
    ],
    tech: [
      'Kotlin',
      'Jetpack Compose',
      'ARCore',
      'Material 3',
      'MVVM',
      'StateFlow',
      'Bully Algorithm',
      'P2P Mesh Networking',
      'Cloud Anchors',
      'Google Nearby Connections',
      'SceneView',
      'Gson',
      'DataStore',
    ],
    featured: true,
    domains: [
      'Systems & Backend',
      'IoT & Embedded',
      'Mobile',
    ],
  },
  {
    id: 'grpc-web-mobile',
    name: 'gRPC Web Mobile',
    summary: '28KB portable Flutter library enabling gRPC-web communication on Android devices',
    period: 'Dec 2025 – Jan 2026',
    type: 'solo',
    repo: 'https://github.com/hoshinoht/grpc_web_mobile',
    responsibilities: [
      'Developed portable 28KB Dart library for gRPC-web on mobile',
    ],
    impact: [
      'Reusable open-source library for Flutter gRPC-web integration',
    ],
    tech: [
      'Dart',
      'Flutter',
      'gRPC-web',
    ],
    featured: false,
    domains: [
      'Systems & Backend',
      'Mobile',
    ],
  },
  {
    id: 'ats-tailor',
    name: 'ATS Tailor',
    summary: 'Semantic resume tailoring engine that matches a YAML index against job descriptions using multi-vector embeddings, hybrid scoring, cross-encoder reranking, and local LLM keyword expansion',
    period: 'Jan 2026 – Present',
    type: 'solo',
    repo: 'https://github.com/hoshinoht/ats-tailor',
    responsibilities: [
      'Built hybrid scoring engine that blends multi-vector semantic embeddings with logarithmic keyword bonuses, tag overlap ratios, and recency weighting',
      'Implemented multi-vector item representations with per-chunk JD weighting and optional cross-encoder reranking',
      'Engineered category-aware LLM keyword expansion with optional two-pass domain inference, limiting expansions to the candidate\'s relevant skill areas',
      'Built embedding cache layer with content-hashed keys for instant re-scoring on index edits',
      'Built 4-panel match visualization and markdown report generation for transparent score breakdowns',
    ],
    impact: [
      'Fully local pipeline — no API calls, runs in <5s on CPU',
      'Open-source tool with profile-based generalization and CLI interface',
      'Category-aware LLM expansion raised tag overlap from 0% to 60-70% on generic JDs; two-pass domain inference further improved precision',
      'Multi-vector embeddings with cross-encoder reranking improved selection accuracy for varied job descriptions',
    ],
    tech: [
      'Python',
      'Jinja2',
      'ollama',
      'Sentence Embeddings',
      'Multi-Vector Retrieval',
      'Hybrid Scoring',
      'Cross-Encoder Reranking',
      'LLM Keyword Expansion',
      'Embedding Cache',
      'sentence-transformers',
      'matplotlib',
      'NumPy',
    ],
    featured: true,
    domains: [
      'ML & AI',
      'Systems & Backend',
    ],
  },
];

export interface SkillCategory {
  name: string;
  skills: { name: string; proficiency: 'advanced' | 'intermediate' | 'familiar' }[];
}

export const skillCategories: SkillCategory[] = [
  {
    name: 'Machine Learning & AI',
    skills: [
      { name: 'Deep Learning', proficiency: 'advanced' },
      { name: 'LSTM / GRU', proficiency: 'advanced' },
      { name: 'LLM / RAG', proficiency: 'intermediate' },
      { name: 'Multi-Agent Systems', proficiency: 'intermediate' },
      { name: 'Federated Learning', proficiency: 'intermediate' },
      { name: 'Scikit-learn', proficiency: 'intermediate' },
      { name: 'TensorFlow', proficiency: 'intermediate' },
      { name: 'Model Fine-Tuning', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'Programming Languages',
    skills: [
      { name: 'Go', proficiency: 'advanced' },
      { name: 'Python', proficiency: 'advanced' },
      { name: 'Rust', proficiency: 'advanced' },
      { name: 'C#', proficiency: 'advanced' },
      { name: 'C', proficiency: 'advanced' },
      { name: 'Java', proficiency: 'familiar' },
      { name: 'C++', proficiency: 'intermediate' },
      { name: 'Kotlin', proficiency: 'intermediate' },
      { name: 'Dart', proficiency: 'intermediate' },
      { name: 'TypeScript', proficiency: 'intermediate' },
      { name: 'SQL', proficiency: 'intermediate' },
      { name: 'Assembly', proficiency: 'familiar' },
    ],
  },
  {
    name: 'Cloud & Infrastructure',
    skills: [
      { name: 'Docker', proficiency: 'advanced' },
      { name: 'Kubernetes', proficiency: 'intermediate' },
      { name: 'AWS', proficiency: 'intermediate' },
      { name: 'GCP', proficiency: 'familiar' },
      { name: 'Firebase', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'Observability & Monitoring',
    skills: [
      { name: 'Prometheus', proficiency: 'advanced' },
      { name: 'Grafana', proficiency: 'advanced' },
      { name: 'Distributed Tracing', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'Architecture & Protocols',
    skills: [
      { name: 'gRPC', proficiency: 'advanced' },
      { name: 'Microservices', proficiency: 'advanced' },
      { name: 'Event-Driven Architecture', proficiency: 'advanced' },
      { name: 'API Gateway Design', proficiency: 'advanced' },
      { name: 'REST API', proficiency: 'advanced' },
      { name: 'WebRTC', proficiency: 'intermediate' },
      { name: 'RabbitMQ', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'IoT & Embedded Systems',
    skills: [
      { name: 'FreeRTOS', proficiency: 'advanced' },
      { name: 'MQTT / MQTT-SN', proficiency: 'advanced' },
      { name: 'ESP32 / ESP-IDF', proficiency: 'intermediate' },
      { name: 'BLE / LoRa', proficiency: 'intermediate' },
      { name: 'SPI / Hardware Drivers', proficiency: 'intermediate' },
      { name: 'Raspberry Pi Pico', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'Databases',
    skills: [
      { name: 'PostgreSQL', proficiency: 'intermediate' },
      { name: 'MongoDB', proficiency: 'intermediate' },
      { name: 'Redis / Valkey', proficiency: 'intermediate' },
      { name: 'SQLite', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'Mobile Development',
    skills: [
      { name: 'Flutter', proficiency: 'intermediate' },
      { name: 'Android (Kotlin)', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'Frontend & Web',
    skills: [
      { name: 'React', proficiency: 'intermediate' },
      { name: 'Tailwind CSS', proficiency: 'intermediate' },
      { name: 'CSS / CSS Modules', proficiency: 'intermediate' },
      { name: 'SCSS / Sass', proficiency: 'familiar' },
    ],
  },
  {
    name: 'Game Development',
    skills: [
      { name: 'Unity', proficiency: 'advanced' },
      { name: 'VR Development', proficiency: 'intermediate' },
      { name: 'Multiplayer / Netcode', proficiency: 'intermediate' },
    ],
  },
  {
    name: 'DevOps & Tooling',
    skills: [
      { name: 'CI/CD', proficiency: 'intermediate' },
      { name: 'CLI Tool Development', proficiency: 'advanced' },
      { name: 'Git / Version Control', proficiency: 'advanced' },
      { name: 'Agile / Scrum', proficiency: 'intermediate' },
      { name: 'Infrastructure as Code', proficiency: 'familiar' },
    ],
  },
  {
    name: 'Testing & QA',
    skills: [
      { name: 'Test Automation', proficiency: 'intermediate' },
      { name: 'TDD / Unit Testing', proficiency: 'intermediate' },
      { name: 'Load Testing', proficiency: 'intermediate' },
    ],
  },
];

export interface Education {
  institution: string;
  degree: string;
  field: string;
  period: string;
}

export const education: Education[] = [
  {
    institution: 'Singapore Institute of Technology – University of Glasgow',
    degree: 'Bachelor of Science with Honours',
    field: 'Computing Science',
    period: 'Sep 2024 – Apr 2027',
  },
  {
    institution: 'Singapore Polytechnic',
    degree: 'Diploma with Merit',
    field: 'Games Design & Development',
    period: 'Mar 2019 – Apr 2022',
  },
  {
    institution: 'Institute of Technical Education',
    degree: 'Nitec',
    field: 'Social Media & Web Development',
    period: '2017 – 2018',
  },
];

export interface Certification {
  name: string;
  issuer: string;
}

export const certifications: Certification[] = [
  { name: 'Fundamentals of Deep Learning', issuer: 'NVIDIA' },
  { name: 'Kubernetes Fundamentals (LFS258)', issuer: 'Dell Technologies' },
  { name: 'AWS Academy Cloud Architecting', issuer: 'Amazon Web Services' },
  { name: 'AWS Academy Cloud Foundations', issuer: 'Amazon Web Services' },
  { name: 'Docker Fundamentals', issuer: 'Dell Technologies' },
];

export const sections = [
  { id: 'hero', label: 'Home' },
  { id: 'experience', label: 'Experience' },
  { id: 'projects', label: 'Projects' },
  { id: 'skills', label: 'Skills' },
  { id: 'education', label: 'Education' },
] as const;

export const domainToSkillCategories: Record<Domain, string[]> = {
  "ML & AI": [
    "Machine Learning & AI"
  ],
  "Cloud & DevOps": [
    "Cloud & Infrastructure",
    "Observability & Monitoring",
    "DevOps & Tooling"
  ],
  "Systems & Backend": [
    "Programming Languages",
    "Architecture & Protocols",
    "Databases"
  ],
  "IoT & Embedded": [
    "Programming Languages",
    "IoT & Embedded Systems"
  ],
  "Mobile": [
    "Programming Languages",
    "Mobile Development"
  ],
  "Game Dev & XR": [
    "Programming Languages",
    "Game Development"
  ],
  "Full Stack & Web": [
    "Programming Languages",
    "Frontend & Web"
  ]
};
